version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  nightly:
    triggers:
      - schedule:
          cron: "*/3 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - cypress/run:
          record: true